version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  strapi:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - ./public/uploads:/app/public/uploads  # Persist uploads
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: "false"
      # Outras variáveis do .env conforme necessário
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    command: bash -c "npm install && npm run develop"

volumes:
  pgdata:
